apiVersion: v1
kind: Service
metadata:
  name: devops-practice
  labels:
    app: devops-practice
spec:
  type: {{ .Values.service.type }}
  selector:
    app: devops-practice
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
